# Generated by Django 3.2.5 on 2021-08-01 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='id',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='imdb_id',
            field=models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
