# Generated by Django 3.2.5 on 2021-09-09 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrating',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
