# Generated by Django 3.2.5 on 2021-09-14 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_myrating_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myrating',
            name='rating',
            field=models.IntegerField(db_index=True, default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
