# Generated by Django 3.2.5 on 2021-07-23 21:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Netflix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netflix', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdb_id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('link', models.TextField()),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('cast', models.TextField()),
                ('plot', models.TextField()),
                ('keywords', models.TextField()),
                ('poster', models.TextField()),
                ('release', models.DateField(default=datetime.date.today)),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_finder.genre')),
                ('mtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_finder.type')),
                ('netflix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_finder.netflix')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_finder.rate')),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_finder.runtime')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_finder.year')),
                ('youtube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_finder.youtube')),
            ],
        ),
    ]
