# Generated by Django 3.2.5 on 2021-09-02 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movie_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
