# Generated by Django 3.2.5 on 2021-09-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_finder', '0002_alter_movie_imdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='votes',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
