# Generated by Django 3.2.5 on 2021-08-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210724_0017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='comments',
            name='email_from',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='email_message_id',
        ),
    ]
