# Generated by Django 3.2 on 2021-04-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
    ]
