# Generated by Django 3.2 on 2021-04-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_auto_20210425_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='added_by',
        ),
    ]
