# Generated by Django 3.1 on 2021-04-27 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('analyzer', '0007_auto_20210427_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commentary',
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzer_group', to='auth.group'),
        ),
    ]
